In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
from keras.layers import *
from keras.models import Model

def build_model():
  x = Input(shape=(64, 64, 3))
  out = x

  out = Flatten()(out)
  out = Dense(512, activation='relu')(out)
  out = Dense(256, activation='relu')(out)
  out = Dense(64, activation='relu')(out)
  out = Dense(1, activation='sigmoid')(out)

  model = Model(x, out)
  return model

In [3]:
model = build_model()
# input_shape = (64, 64, 3)
# model = keras.Sequential()
# model.add(keras.layers.Conv2D(32, kernel_size=(3, 3), padding="same", 
#                  activation='relu',
#                  input_shape=input_shape))
# model.add(keras.layers.MaxPooling2D(pool_size=(2, 2)))
# model.add(keras.layers.Dropout(0.25))
# model.add(keras.layers.Conv2D(64, (3, 3), activation='relu'))
# model.add(keras.layers.MaxPooling2D(pool_size=(2, 2)))
# model.add(keras.layers.Dropout(0.25))
# model.add(keras.layers.Flatten())
# model.add(keras.layers.Dense(256, activation='relu'))
# model.add(keras.layers.Dropout(0.5))
# model.add(keras.layers.Dense(1, activation='sigmoid'))

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 64, 64, 3)]       0         
                                                                 
 flatten (Flatten)           (None, 12288)             0         
                                                                 
 dense (Dense)               (None, 512)               6291968   
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 64)                16448     
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 6,439,809
Trainable params: 6,439,809
Non-train

In [4]:
from keras.preprocessing.image import ImageDataGenerator

In [5]:
Generator = ImageDataGenerator(rescale=1/255.)


In [7]:
train_gen = Generator.flow_from_directory(r'C:\Users\ADMIN\Downloads\deeplearning\python_catdog\train\train', target_size=(64,64),
                                          batch_size=32,
                                          class_mode='binary')

val_gen = Generator.flow_from_directory(r'C:\Users\ADMIN\Downloads\deeplearning\python_catdog\validation\validation', target_size=(64,64),
                                          batch_size=32,
                                          class_mode='binary')

Found 25000 images belonging to 2 classes.
Found 25000 images belonging to 2 classes.


In [8]:
epochs = 2
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(train_gen, 
                    epochs=epochs, 
                    validation_data=val_gen)

Epoch 1/2
782/782 [==============================] - 155s 198ms/step - loss: 0.7388 - accuracy: 0.5527 - val_loss: 0.6836 - val_accuracy: 0.5317
Epoch 2/2
782/782 [==============================] - 131s 167ms/step - loss: 0.6675 - accuracy: 0.5965 - val_loss: 0.6672 - val_accuracy: 0.6037


In [9]:
model.save(r"C:\Users\ADMIN\Downloads\deeplearning\python_catdog\train\train\my_model-220914-ver1.h5")

model load

In [1]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [5]:
from keras.preprocessing.image import ImageDataGenerator

In [7]:
Generator = ImageDataGenerator(rescale=1/255.)


In [14]:
train_gen = Generator.flow_from_directory(r'C:\Users\ADMIN\Downloads\deeplearning\python_catdog\train\train', target_size=(64,64),
                                          batch_size=32,
                                          class_mode='binary')

val_gen = Generator.flow_from_directory(r'C:\Users\ADMIN\Downloads\deeplearning\python_catdog\validation\validation', target_size=(64,64),
                                          batch_size=32,
                                          class_mode='binary')

Found 25000 images belonging to 2 classes.
Found 25000 images belonging to 2 classes.


In [2]:
model = load_model(r'C:\Users\ADMIN\Downloads\deeplearning\python_catdog\train\train\my_model-220914-ver1.h5')


In [3]:
import matplotlib.pyplot as plt
%matplotlib inline 

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(1, len(loss) + 1)

plt.figure()

plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'r', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()

plt.show()

NameError: name 'history' is not defined

In [8]:
test_gen = Generator.flow_from_directory (r'C:\Users\ADMIN\Downloads\deeplearning\python_catdog\test1', target_size=(64,64),
                                          batch_size=32,
                                          class_mode='binary')

Found 12500 images belonging to 1 classes.


In [9]:
score = model.evaluate(test_gen, verbose=0)
print(f'Test loss: {score[0]:.3f}')
print(f'Test accuracy: {score[1]:.3f}')

Test loss: 0.669
Test accuracy: 0.445


In [10]:
import numpy as np

x_tests, y_tests = [], []
for i in range(len(test_gen)):
  x_test, y_test = next(test_gen)
  x_tests.append(x_test)
  y_tests.append(y_test)

x_test = np.concatenate(x_tests, axis=0)
y_test = np.concatenate(y_tests, axis=0)

print(x_test.shape)
print(y_test.shape)

(12500, 64, 64, 3)
(12500,)


In [18]:
pred = model.predict(x_test[:4])

print(pred)
# for i in range(4):
#    plt.imshow(x_test[i])
#    plt.title(pred[i])
#    plt.show()

1/1 [==============================] - 0s 14ms/step
[[0.4891212]
 [0.4110585]
 [0.4743257]
 [0.5145591]]


In [15]:
train_gen.class_indices

{'cats': 0, 'dogs': 1}

In [33]:
import glob
fileList = glob.glob('C:/Users/ADMIN/Downloads/deeplearning/python_catdog/test1')
print(fileList)

['C:/Users/ADMIN/Downloads/deeplearning/python_catdog/test1']


In [34]:
import glob
fileList = glob.glob('C:/Users/ADMIN/Downloads/deeplearning/python_catdog/test1')

results = []

for file_path in fileList:
    results.append(file_path)

ex51 = pd.DataFrame(results)
ex52 = pd.DataFrame(fileList)   

In [35]:
print.head(ex51)

AttributeError: 'builtin_function_or_method' object has no attribute 'head'

In [37]:
print(ex51)

                                                   0
0  C:/Users/ADMIN/Downloads/deeplearning/python_c...


In [38]:
print(ex52)

                                                   0
0  C:/Users/ADMIN/Downloads/deeplearning/python_c...


In [41]:
ex61 = pd.DataFrame(x_tests)

C:\Users\ADMIN\anaconda3\lib\site-packages\pandas\core\internals\construction.py:576: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array([convert(v) for v in values])


In [39]:
print(x_test)

[[[[0.42352945 0.427451   0.35686275]
   [0.36862746 0.37254903 0.3019608 ]
   [0.41176474 0.4156863  0.34509805]
   ...
   [0.10196079 0.07843138 0.03137255]
   [0.06666667 0.03137255 0.00392157]
   [0.04313726 0.0509804  0.        ]]

  [[0.47450984 0.4784314  0.40784317]
   [0.49803925 0.5019608  0.43137258]
   [0.4784314  0.48235297 0.41176474]
   ...
   [0.1254902  0.07450981 0.03921569]
   [0.09803922 0.0627451  0.03529412]
   [0.04705883 0.04313726 0.03529412]]

  [[0.48235297 0.48627454 0.4156863 ]
   [0.47450984 0.4784314  0.40784317]
   [0.4784314  0.48235297 0.41176474]
   ...
   [0.10980393 0.04313726 0.01176471]
   [0.11764707 0.08235294 0.05490196]
   [0.0509804  0.03137255 0.01568628]]

  ...

  [[0.37647063 0.38431376 0.34117648]
   [0.37254903 0.3803922  0.3372549 ]
   [0.38431376 0.38431376 0.34509805]
   ...
   [0.07843138 0.08235294 0.0627451 ]
   [0.34901962 0.3529412  0.33333334]
   [0.37647063 0.36078432 0.3254902 ]]

  [[0.37647063 0.38431376 0.34117648]
   [0.3

In [29]:
img_path = 'C:/Users/ADMIN/Downloads/deeplearning/python_catdog/test1'

In [30]:
def infer(img_path:str):
    # Create the array of the right shape to feed into the keras model
    # The 'length' or number of images you can put into the array is
    # determined by the first position in the shape tuple, in this case 1.
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
    # Replace this with the path to your image
    image = Image.open(img_path)
    #resize the image to a 224x224 with the same strategy as in TM2:
    #resizing the image to be at least 224x224 and then cropping from the center
    size = (224, 224)
    image = ImageOps.fit(image, size, Image.ANTIALIAS)

    #turn the image into a numpy array
    image_array = np.asarray(image)
    # Normalize the image
    normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
    # Load the image into the array
    data[0] = normalized_image_array

    # run the inference
    prediction = model.predict(data)
    
    return prediction[0]

In [32]:
import glob
fileList = glob.glob('C:/Users/ADMIN/Downloads/deeplearning/python_catdog/test1')

results = []

for file_path in fileList:
    results.append(infer(file_path))

ex51 = pd.DataFrame(results)
ex52 = pd.DataFrame(fileList)   

PermissionError: [Errno 13] Permission denied: 'C:/Users/ADMIN/Downloads/deeplearning/python_catdog/test1'